# Yaml file is similar to JSON file
# We can write configuration in terms of key and values in YAML file

# Whenever we are pushing anything in the main branch then only we need to run this workflow
name: Build and push image to ECR
on: 
  push:
    branches:
      # make sure to update the main branch name -  main branch name is main
      - main
     

jobs: 
  build-and-push-ecr-image:
    # Use ubuntu machine
    name: Build Image
    runs-on: ubuntu-latest # server name

    steps: 
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Utilities
      # Update the machine
      run: |
        sudo apt-get update
        sudo apt-get install -y jq unzip

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # configure access and secret key in order to make connection from github server to AWS server
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # needs to be updated for new project from AWS server
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # needs to be updated for new project from AWS server
        aws-region: eu-north-1 # needs to be updated for new project from AWS server
      
      # Logging in to ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: phishingdomaindetection # ECR Repository name from AWS
        IMAGE_TAG: latest
      
      # Command for building the image
      # pushing the image to AWS ECR repo
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . 
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  